### ISSUE TITLE
No such file or directory: '/home/jenkins/workspace/gate-rpm-packaging-tox-lint/.tox/lint/local/share/spec-cleaner/excludes-bracketing.txt

### ISSUE THREAD

**Issue by toabctl** [openSUSE/spec-cleaner#137]
This happens when installing spec-cleaner in a venv in /usr/local . See http://logs.openstack.org/85/311285/10/check/gate-rpm-packaging-tox-lint/672166b/console.html

**Comment by toabctl** [comment]
Looks like the problem is that ```sysconfig.get_path('data')``` is ```/home/jenkins/workspace/gate-rpm-packaging-tox-lint/.tox/lint/local``` (See [debug output](http://logs.openstack.org/85/311285/12/check/gate-rpm-packaging-tox-lint/2287b0e/console.html)).
Instead of using ```sysconfig.get_path('data``` we could use ```sys.prefix```.

**Comment by matejcik** [comment]
so where is the ".tox/lint/local" part coming from?

are you trying to use system-installed spec-cleaner in a different, local venv?

**Comment by toabctl** [comment]
> so where is the ".tox/lint/local" part coming from?

Good question. I'm not sure how the test environment is setup. Here is some more debug output: http://logs.openstack.org/85/311285/13/check/gate-rpm-packaging-tox-lint/3385584/console.html

> 
> are you trying to use system-installed spec-cleaner in a different, local venv?

No. There's no system-installed spec-cleaner. Just spec-cleaner installed via pip.

**Comment by matejcik** [comment]
unfortunately the log files seem to be gone now.

thing is, i don't understand how you can even get `get_path('data')` to be different from `sys.prefix`, and i would really prefer to know if your PR is a bugfix or a workaround ;) that would allow us, for instance, to support more weird configurations in the future

**Comment by toabctl** [comment]
> unfortunately the log files seem to be gone now.

The log is compressed now: http://logs.openstack.org/85/311285/13/check/gate-rpm-packaging-tox-lint/3385584/console.html.gz

**Comment by matejcik** [comment]
can you get output of "python -m sysconfig"?

**Comment by toabctl** [comment]
> can you get output of "python -m sysconfig"?

http://logs.openstack.org/85/311285/14/check/gate-rpm-packaging-tox-lint/e95fe6a/console.html (maybe with .gz at the end, depends when you open the log)

**Comment by toabctl** [comment]
@matejcik friendly ping ...

**Comment by matejcik** [comment]
yeah, yeah :)

this is actually a bug in the interplay of pip (which doesn't respect sysconfig path schemes), debian (which created a `posix_local` path scheme), and virtualenv (which is trying and failing to properly handle this mess). You could configure your system not to use the `posix_local` scheme, but unfortunately, all debians are broken out-of-the-box.

(the meta problem here is that python packaging format never expects anyone to put data into `{prefix}/share`... i'm not even sure whether this is worth reporting to the virtualenv team)

i suppose your PR is as good as any for this, an alternative would be to look in default scheme first and then `posix_prefix`, instead of sys.prefix directly, but in practice, it's one and the same.
